config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'

  #get 'contacts' => 'contacts#new'
  resource :contacts, only: [ :new, :create ], path_names: { :new => '' }
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end

  def create
    render plain: params[:article].inspect
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new

  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render :new
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/new.html.erb
<div class="container mt-5 mb-5">
  <h2>New article</h2>
</div>

<div class="container">
  <%= form_for :article, url: articles_path do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <%= f.submit %>
  <% end %>
</div>

app/views/contacts/create.html.erb
<div class="container mt-5 mb-5">
  <h2>Thanks</h2>
</div>

app/views/contacts/new.html.erb
<div class="container mt-5 mb-5">
  <h2>Contact us</h2>
</div>

<div class="container">
  <%= form_for :contact, url: contacts_path do |f| %>
    <% if @contact && @contact.errors.any? %>
      <p>
        <ul>
          <% @contact.errors.full_messages.each do |msg| %>
            <small>
              <li><%= msg %></li>
            </small>
          <% end %>
        </ul>
      </p>
    <% end %>
    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :message %><br>
      <%= f.text_area :message %>
    </p>

    <%= f.submit 'Send message' %>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>